[build]
  command: npm run build
  commandOrigin: config
  publish: /opt/build/repo/dist
  publishOrigin: config
  plugins:
 - inputs: {}
   origin: ui
   package: netlify-purge-cloudflare-on-deploy

